name: "Validate"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-hassfest:
    name: With hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: With HACS action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py

      - name: HACS Validation
        uses: hacs/action@main
        with:
          ignore: brands
          category: integration
          comment: True
